# it deploys a ingress controller pod to monitor ingress rules and operate based on that
# it also creates an external ip by default and assign it to the default load balancer (in node resource group) created as part of cluster creation.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: main
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.7.2

  # default override
  values:
    controller:
      service:
        annotations: 
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  interval: 1m0s

