apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: main
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #     - aks.cloudwise.net.au
  #   secretName: ingress-tls-csi
  rules:
    # - host: aks.cloudwise.net.au
    - http:
      paths:
        - path: /hello-world-one(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: aks-helloworld-one
              port:
                number: 80
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: aks-helloworld-one
              port:
                number: 80
