apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-utility
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql-utility
  template:
    metadata:
      labels:
        app: psql-utility
    spec:
      containers:
        - name: psql-utility
          image: postgres:13-bullseye
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 80
