kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ado-svc-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: ado-svc-role-binding
# subjects:
#   - apiGroup: rbac.authorization.k8s.io
#     kind: User
#     # app aks-auth-service-principal object id
#     # name: 
#     name: 5d365c7b-29bb-4f6f-ad56-8361daf8aa02
# roleRef:
#   kind: ClusterRole
#   name: ado-svc-role
#   apiGroup: rbac.authorization.k8s.io
