kind: Namespace
apiVersion: v1
metadata:
  name: main
  labels:
    name: main

---
# dev and sre ns added for entra ID integration lab
kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    name: dev

---
kind: Namespace
apiVersion: v1
metadata:
  name: sre
  labels:
    name: sre
    # set PSS to restricted
    # https://samos-it.com/posts/Preventing-Privileged-pods-using-Pod-Security-Admission-Standards.html
    pod-security.kubernetes.io/enforce: restricted
